name : first_workflow

on:
 #[push,pull_request]
  push:
    branches:
     - main

jobs:
  echo-statement:
    runs-on: ubuntu-latest
    steps:
     - name: echo
       run: echo "first workflow"
  workflow:
    needs: echo-statement
    runs-on: windows-latest
    steps:
     - name: echo
       run: echo "first workflow test"
